export const HEALTH_METRIC_CATEGORY_VALUES = [
  'METABOLIC',
  'LIPID',
  'GLUCOSE',
  'LIVER',
  'KIDNEY',
  'URINE',
  'HORMONE',
  'BLOOD',
  'THYROID',
  'CARDIO',
  'BODY_COMP',
] as const;

export type HealthMetricCategory = (typeof HEALTH_METRIC_CATEGORY_VALUES)[number];

export type HealthMetricCatalogItem = {
  key: string;
  nameZh: string;
  aliases: string[];
  unit: string;
  category: HealthMetricCategory;
  fitnessRelevant: boolean;
  refLow?: number;
  refHigh?: number;
  /** 危急低值：命中后评估 severity 升 URGENT。仅填有明确临床危急阈值的指标。 */
  criticalLow?: number;
  /** 危急高值：命中后评估 severity 升 URGENT。仅填有明确临床危急阈值的指标。 */
  criticalHigh?: number;
};

// 参考区间来自公开临床检验常用成人范围；不同实验室、性别与年龄可能不同，展示时优先采用报告原文参考值。
export const HEALTH_METRIC_CATALOG: readonly HealthMetricCatalogItem[] = [
  {
    key: 'BMI',
    nameZh: '身体质量指数',
    aliases: ['BMI', '身体质量指数', '体质指数'],
    unit: 'kg/m2',
    category: 'BODY_COMP',
    fitnessRelevant: true,
    refLow: 18.5,
    refHigh: 23.9,
  },
  {
    key: 'BODY_FAT_PERCENT',
    nameZh: '体脂率',
    aliases: ['体脂率', '体脂百分比', 'Body Fat %', 'PBF'],
    unit: '%',
    category: 'BODY_COMP',
    fitnessRelevant: true,
  },
  {
    key: 'SBP',
    nameZh: '收缩压',
    aliases: ['收缩压', '高压', 'SBP', 'Systolic Blood Pressure'],
    unit: 'mmHg',
    category: 'CARDIO',
    fitnessRelevant: true,
    refLow: 90,
    refHigh: 139,
    // 高血压急症 / 休克常见危急阈值
    criticalLow: 80,
    criticalHigh: 180,
  },
  {
    key: 'DBP',
    nameZh: '舒张压',
    aliases: ['舒张压', '低压', 'DBP', 'Diastolic Blood Pressure'],
    unit: 'mmHg',
    category: 'CARDIO',
    fitnessRelevant: true,
    refLow: 60,
    refHigh: 89,
    criticalLow: 50,
    criticalHigh: 120,
  },
  {
    key: 'FPG',
    nameZh: '空腹血糖',
    aliases: ['空腹血糖', 'FPG', 'GLU'],
    unit: 'mmol/L',
    category: 'GLUCOSE',
    fitnessRelevant: true,
    refLow: 3.9,
    refHigh: 6.1,
    // 临床检验危急值常见：低血糖 <2.8，高血糖危象 >22.2 mmol/L
    criticalLow: 2.8,
    criticalHigh: 22.2,
  },
  {
    key: 'HBA1C',
    nameZh: '糖化血红蛋白',
    aliases: ['糖化血红蛋白', 'HbA1c', 'HBA1C'],
    unit: '%',
    category: 'GLUCOSE',
    fitnessRelevant: true,
    refLow: 4,
    refHigh: 6,
  },
  {
    key: 'TC',
    nameZh: '总胆固醇',
    aliases: ['总胆固醇', 'TC', 'CHO', 'TCHO'],
    unit: 'mmol/L',
    category: 'LIPID',
    fitnessRelevant: true,
    refHigh: 5.2,
  },
  {
    key: 'TG',
    nameZh: '甘油三酯',
    aliases: ['甘油三酯', 'TG', 'TRIG'],
    unit: 'mmol/L',
    category: 'LIPID',
    fitnessRelevant: true,
    refHigh: 1.7,
  },
  {
    key: 'HDL',
    nameZh: '高密度脂蛋白胆固醇',
    aliases: ['高密度脂蛋白', '高密度脂蛋白胆固醇', 'HDL', 'HDL-C'],
    unit: 'mmol/L',
    category: 'LIPID',
    fitnessRelevant: true,
    refLow: 1.04,
  },
  {
    key: 'LDL',
    nameZh: '低密度脂蛋白胆固醇',
    aliases: ['低密度脂蛋白', '低密度脂蛋白胆固醇', 'LDL', 'LDL-C'],
    unit: 'mmol/L',
    category: 'LIPID',
    fitnessRelevant: true,
    refHigh: 3.4,
  },
  {
    key: 'UA',
    nameZh: '尿酸',
    aliases: ['尿酸', 'UA', 'Uric Acid'],
    unit: 'umol/L',
    category: 'KIDNEY',
    fitnessRelevant: true,
    refLow: 150,
    refHigh: 420,
  },
  {
    key: 'ALT',
    nameZh: '丙氨酸氨基转移酶',
    aliases: ['丙氨酸氨基转移酶', '谷丙转氨酶', 'ALT', 'GPT'],
    unit: 'U/L',
    category: 'LIVER',
    fitnessRelevant: true,
    refLow: 7,
    refHigh: 40,
    // 约 10× 参考上限，提示急性肝损伤需就医
    criticalHigh: 400,
  },
  {
    key: 'AST',
    nameZh: '天门冬氨酸氨基转移酶',
    aliases: ['天门冬氨酸氨基转移酶', '谷草转氨酶', 'AST', 'GOT'],
    unit: 'U/L',
    category: 'LIVER',
    fitnessRelevant: true,
    refLow: 13,
    refHigh: 35,
    criticalHigh: 400,
  },
  {
    key: 'GGT',
    nameZh: '谷氨酰转移酶',
    aliases: ['谷氨酰转移酶', 'γ-谷氨酰转移酶', 'GGT', 'γ-GT'],
    unit: 'U/L',
    category: 'LIVER',
    fitnessRelevant: true,
    refLow: 10,
    refHigh: 60,
  },
  {
    key: 'ALB',
    nameZh: '白蛋白',
    aliases: ['白蛋白', 'ALB'],
    unit: 'g/L',
    category: 'LIVER',
    fitnessRelevant: true,
    refLow: 40,
    refHigh: 55,
  },
  {
    key: 'TP',
    nameZh: '总蛋白',
    aliases: ['总蛋白', 'TP'],
    unit: 'g/L',
    category: 'LIVER',
    fitnessRelevant: true,
    refLow: 65,
    refHigh: 85,
  },
  {
    key: 'ALP',
    nameZh: '碱性磷酸酶',
    aliases: ['碱性磷酸酶', 'ALP'],
    unit: 'U/L',
    category: 'LIVER',
    fitnessRelevant: true,
    refLow: 45,
    refHigh: 125,
  },
  {
    key: 'AG_RATIO',
    nameZh: '白球比',
    aliases: ['白球比', 'A/G', 'AG'],
    unit: '',
    category: 'LIVER',
    fitnessRelevant: false,
    refLow: 1.2,
    refHigh: 2.4,
  },
  {
    key: 'CREATININE',
    nameZh: '肌酐',
    aliases: ['肌酐', 'CREA', 'Cr', 'Creatinine'],
    unit: 'umol/L',
    category: 'KIDNEY',
    fitnessRelevant: true,
    refLow: 57,
    refHigh: 111,
    // 约 5 mg/dL，临床肌酐危急值常用阈值
    criticalHigh: 442,
  },
  {
    key: 'EGFR',
    nameZh: '估算肾小球滤过率',
    aliases: ['估算肾小球滤过率', 'eGFR', 'GFR'],
    unit: 'mL/min/1.73m2',
    category: 'KIDNEY',
    fitnessRelevant: true,
    refLow: 90,
    // CKD G5 水平，需尽快就医评估
    criticalLow: 15,
  },
  {
    key: 'URINE_GLU',
    nameZh: '尿葡萄糖',
    aliases: ['尿葡萄糖', '尿糖', '葡萄糖'],
    unit: 'mmol/L',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'URINE_PROTEIN',
    nameZh: '尿蛋白',
    aliases: ['尿蛋白', '蛋白质'],
    unit: '',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'URINE_KETONE',
    nameZh: '尿酮体',
    aliases: ['酮体', '尿酮体'],
    unit: 'mmol/L',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'URINE_BILIRUBIN',
    nameZh: '尿胆红素',
    aliases: ['胆红素', '尿胆红素'],
    unit: 'umol/L',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'URINE_UROBILINOGEN',
    nameZh: '尿胆元',
    aliases: ['尿胆元', '尿胆原'],
    unit: 'umol/L',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'URINE_OCCULT_BLOOD',
    nameZh: '尿隐血',
    aliases: ['隐血', '尿隐血'],
    unit: 'Cells/uL',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'URINE_WBC',
    nameZh: '尿白细胞',
    aliases: ['尿白细胞'],
    unit: 'Cells/uL',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'URINE_RBC',
    nameZh: '尿红细胞',
    aliases: ['红细胞(镜检)', '尿红细胞'],
    unit: 'HP',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'URINE_SG',
    nameZh: '尿比重',
    aliases: ['比重', '尿比重'],
    unit: '',
    category: 'URINE',
    fitnessRelevant: false,
    refLow: 1.005,
    refHigh: 1.03,
  },
  {
    key: 'URINE_PH',
    nameZh: '尿酸碱度',
    aliases: ['PH值', 'pH值', '尿酸碱度'],
    unit: '',
    category: 'URINE',
    fitnessRelevant: false,
    refLow: 5.0,
    refHigh: 8.0,
  },
  {
    key: 'URINE_NITRITE',
    nameZh: '亚硝酸盐',
    aliases: ['亚硝酸盐'],
    unit: '',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'URINE_ASCORBIC',
    nameZh: '尿抗坏血酸',
    aliases: ['抗坏血酸', '尿抗坏血酸'],
    unit: 'mmol/L',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'URINE_COLOR',
    nameZh: '尿液颜色',
    aliases: ['颜色', '尿颜色'],
    unit: '',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'URINE_TURBIDITY',
    nameZh: '尿液浊度',
    aliases: ['浊度', '尿浊度'],
    unit: '',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'URINE_CRYSTALS',
    nameZh: '尿结晶',
    aliases: ['结晶(镜检)', '结晶', '尿结晶'],
    unit: 'HP',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'URINE_CASTS',
    nameZh: '尿管型',
    aliases: ['管型(镜检)', '管型', '尿管型'],
    unit: 'LP',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'URINE_SQUAMOUS_EPI',
    nameZh: '鳞状上皮细胞',
    aliases: ['鳞状上皮细胞(镜检)', '鳞状上皮细胞'],
    unit: 'HP',
    category: 'URINE',
    fitnessRelevant: false,
  },
  {
    key: 'WBC',
    nameZh: '白细胞',
    aliases: ['白细胞', '白细胞计数', '白细胞数', 'WBC'],
    unit: '10^9/L',
    category: 'BLOOD',
    fitnessRelevant: true,
    refLow: 3.5,
    refHigh: 9.5,
    criticalLow: 2.0,
    criticalHigh: 30,
  },
  {
    key: 'RBC',
    nameZh: '红细胞',
    aliases: ['红细胞', '红细胞计数', '红细胞数', 'RBC'],
    unit: '10^12/L',
    category: 'BLOOD',
    fitnessRelevant: true,
    refLow: 4.3,
    refHigh: 5.8,
  },
  {
    key: 'PLT',
    nameZh: '血小板',
    aliases: ['血小板', '血小板计数', 'PLT'],
    unit: '10^9/L',
    category: 'BLOOD',
    fitnessRelevant: true,
    refLow: 100,
    refHigh: 300,
    criticalLow: 50,
  },
  {
    key: 'HCT',
    nameZh: '红细胞压积',
    aliases: ['红细胞压积', '血细胞比容', 'HCT'],
    unit: '%',
    category: 'BLOOD',
    fitnessRelevant: true,
    refLow: 40,
    refHigh: 50,
  },
  {
    key: 'MCV',
    nameZh: '红细胞平均体积',
    aliases: ['红细胞平均体积', '平均红细胞体积', 'MCV'],
    unit: 'fL',
    category: 'BLOOD',
    fitnessRelevant: true,
    refLow: 82,
    refHigh: 100,
  },
  {
    key: 'MCH',
    nameZh: '平均血红蛋白量',
    aliases: ['平均血红蛋白量', '平均血红蛋白含量', 'MCH'],
    unit: 'pg',
    category: 'BLOOD',
    fitnessRelevant: true,
    refLow: 27,
    refHigh: 34,
  },
  {
    key: 'MCHC',
    nameZh: '平均血红蛋白浓度',
    aliases: ['平均血红蛋白浓度', 'MCHC'],
    unit: 'g/L',
    category: 'BLOOD',
    fitnessRelevant: true,
    refLow: 316,
    refHigh: 354,
  },
  {
    key: 'HGB',
    nameZh: '血红蛋白',
    aliases: ['血红蛋白', '血色素', 'HGB'],
    unit: 'g/L',
    category: 'BLOOD',
    fitnessRelevant: true,
    refLow: 120,
    refHigh: 160,
    criticalLow: 60,
    criticalHigh: 200,
  },
  {
    key: 'NEUT',
    nameZh: '中性粒细胞',
    aliases: ['中性粒细胞', '中性细胞', '中性粒细胞数', '中性细胞数', 'NEUT'],
    unit: '10^9/L',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 1.8,
    refHigh: 6.3,
  },
  {
    key: 'NEUT_PCT',
    nameZh: '中性粒细胞比率',
    aliases: ['中性粒细胞比率', '中性细胞比率', 'NEUT%'],
    unit: '%',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 40,
    refHigh: 75,
  },
  {
    key: 'LYMPH',
    nameZh: '淋巴细胞',
    aliases: ['淋巴细胞', '淋巴细胞数', 'LYMPH'],
    unit: '10^9/L',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 1.1,
    refHigh: 3.2,
  },
  {
    key: 'LYMPH_PCT',
    nameZh: '淋巴细胞比率',
    aliases: ['淋巴细胞比率', 'LYMPH%'],
    unit: '%',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 20,
    refHigh: 50,
  },
  {
    key: 'MONO',
    nameZh: '单核细胞',
    aliases: ['单核细胞', '单核细胞数', 'MONO'],
    unit: '10^9/L',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 0.1,
    refHigh: 0.6,
  },
  {
    key: 'MONO_PCT',
    nameZh: '单核细胞比率',
    aliases: ['单核细胞比率', 'MONO%'],
    unit: '%',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 3,
    refHigh: 10,
  },
  {
    key: 'EOS',
    nameZh: '嗜酸性粒细胞',
    aliases: ['嗜酸性粒细胞', '嗜酸性粒细胞数', 'EOS'],
    unit: '10^9/L',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 0.02,
    refHigh: 0.52,
  },
  {
    key: 'EOS_PCT',
    nameZh: '嗜酸性粒细胞比率',
    aliases: ['嗜酸性粒细胞比率', 'EOS%'],
    unit: '%',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 0.4,
    refHigh: 8,
  },
  {
    key: 'BASO',
    nameZh: '嗜碱性粒细胞',
    aliases: ['嗜碱性粒细胞', '嗜碱性粒细胞数', 'BASO'],
    unit: '10^9/L',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 0,
    refHigh: 0.06,
  },
  {
    key: 'BASO_PCT',
    nameZh: '嗜碱性粒细胞比率',
    aliases: ['嗜碱性粒细胞比率', 'BASO%'],
    unit: '%',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 0,
    refHigh: 1,
  },
  {
    key: 'MPV',
    nameZh: '平均血小板体积',
    aliases: ['平均血小板体积', 'MPV'],
    unit: 'fL',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 6.5,
    refHigh: 12,
  },
  {
    key: 'PCT',
    nameZh: '血小板压积',
    aliases: ['血小板压积'],
    unit: '%',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 0.108,
    refHigh: 0.282,
  },
  {
    key: 'PDW',
    nameZh: '血小板分布宽度',
    aliases: ['血小板分布宽度', 'PDW'],
    unit: 'fL',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 9,
    refHigh: 17,
  },
  {
    key: 'PLCR',
    nameZh: '大型血小板比率',
    aliases: ['大型血小板比率', 'P-LCR', 'PLCR'],
    unit: '%',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 11,
    refHigh: 45,
  },
  {
    key: 'RDW_CV',
    nameZh: '红细胞分布宽度变异系数',
    aliases: ['红细胞分布宽度变异系数', 'RDW-CV', 'RDWCV'],
    unit: '%',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 11,
    refHigh: 16,
  },
  {
    key: 'RDW_SD',
    nameZh: '红细胞分布宽度标准差',
    aliases: ['红细胞分布宽度标准差', 'RDW-SD', 'RDWSD'],
    unit: 'fL',
    category: 'BLOOD',
    fitnessRelevant: false,
    refLow: 35,
    refHigh: 56,
  },
  {
    key: 'TSH',
    nameZh: '促甲状腺激素',
    aliases: ['促甲状腺激素', 'TSH'],
    unit: 'mIU/L',
    category: 'THYROID',
    fitnessRelevant: true,
    refLow: 0.27,
    refHigh: 4.2,
  },
  {
    key: 'RHR',
    nameZh: '静息心率',
    aliases: ['静息心率', 'RHR', 'Resting Heart Rate'],
    unit: 'bpm',
    category: 'CARDIO',
    fitnessRelevant: true,
    refLow: 60,
    refHigh: 100,
  },
  {
    key: 'TESTOSTERONE',
    nameZh: '睾酮',
    aliases: ['睾酮', '总睾酮', 'Testosterone', 'TT'],
    unit: 'nmol/L',
    category: 'HORMONE',
    fitnessRelevant: true,
  },
  {
    key: 'CORTISOL',
    nameZh: '皮质醇',
    aliases: ['皮质醇', 'Cortisol'],
    unit: 'nmol/L',
    category: 'HORMONE',
    fitnessRelevant: true,
  },
  {
    key: 'SHBG',
    nameZh: '性激素结合球蛋白',
    aliases: ['性激素结合球蛋白', 'SHBG'],
    unit: 'nmol/L',
    category: 'HORMONE',
    fitnessRelevant: true,
  },
];

const normalizedAliasToKey = new Map<string, string>();
for (const metric of HEALTH_METRIC_CATALOG) {
  normalizedAliasToKey.set(normalizeMetricName(metric.key), metric.key);
  normalizedAliasToKey.set(normalizeMetricName(metric.nameZh), metric.key);
  for (const alias of metric.aliases) {
    normalizedAliasToKey.set(normalizeMetricName(alias), metric.key);
  }
}

export function getMetricByKey(key: string): HealthMetricCatalogItem | undefined {
  return HEALTH_METRIC_CATALOG.find((metric) => metric.key === key);
}

export function resolveMetricKey(rawName: string): string | undefined {
  return normalizedAliasToKey.get(normalizeMetricName(rawName));
}

function normalizeMetricName(value: string): string {
  return value.toLowerCase().replace(/[\s_\-()（）·.]/g, '');
}
