import {
  ExerciseDifficulty,
  ExerciseEquipment,
  PrimaryMuscle,
  type Prisma,
} from '../../../src/generated';

export const ABS_EXERCISES: Prisma.ExerciseCreateManyInput[] = [
  {
    nameZh: '悬垂举腿',
    nameEn: 'Hanging Leg Raise',
    primaryMuscle: PrimaryMuscle.ABS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.BODYWEIGHT,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '卷腹',
    nameEn: 'Crunch',
    primaryMuscle: PrimaryMuscle.ABS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.BODYWEIGHT,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '平板支撑',
    nameEn: 'Plank',
    primaryMuscle: PrimaryMuscle.ABS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.BODYWEIGHT,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '俄罗斯转体',
    nameEn: 'Russian Twist',
    primaryMuscle: PrimaryMuscle.ABS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.BODYWEIGHT,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '龙门架卷腹',
    nameEn: 'Cable Crunch',
    primaryMuscle: PrimaryMuscle.ABS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.CABLE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '自行车卷腹',
    nameEn: 'Bicycle Crunch',
    primaryMuscle: PrimaryMuscle.ABS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.BODYWEIGHT,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '腹肌轮',
    nameEn: 'Ab Wheel Rollout',
    primaryMuscle: PrimaryMuscle.ABS,
    secondaryMuscles: [PrimaryMuscle.SHOULDER],
    equipment: ExerciseEquipment.OTHER,
    difficulty: ExerciseDifficulty.ADVANCED,
    isPreset: true,
  },
];
