import {
  ExerciseDifficulty,
  ExerciseEquipment,
  PrimaryMuscle,
  type Prisma,
} from '../../../src/generated';

export const BACK_EXERCISES: Prisma.ExerciseCreateManyInput[] = [
  {
    nameZh: '引体向上',
    nameEn: 'Pull-up',
    primaryMuscle: PrimaryMuscle.BACK,
    secondaryMuscles: [PrimaryMuscle.BICEPS, PrimaryMuscle.FOREARMS],
    equipment: ExerciseEquipment.BODYWEIGHT,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '杠铃硬拉',
    nameEn: 'Barbell Deadlift',
    primaryMuscle: PrimaryMuscle.BACK,
    secondaryMuscles: [PrimaryMuscle.HAMSTRINGS, PrimaryMuscle.GLUTES, PrimaryMuscle.FOREARMS],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.ADVANCED,
    isPreset: true,
  },
  {
    nameZh: '杠铃划船',
    nameEn: 'Barbell Row',
    primaryMuscle: PrimaryMuscle.BACK,
    secondaryMuscles: [PrimaryMuscle.BICEPS, PrimaryMuscle.FOREARMS],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '高位下拉',
    nameEn: 'Lat Pulldown',
    primaryMuscle: PrimaryMuscle.BACK,
    secondaryMuscles: [PrimaryMuscle.BICEPS],
    equipment: ExerciseEquipment.CABLE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '坐姿划船',
    nameEn: 'Seated Cable Row',
    primaryMuscle: PrimaryMuscle.BACK,
    secondaryMuscles: [PrimaryMuscle.BICEPS],
    equipment: ExerciseEquipment.CABLE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '直臂下压',
    nameEn: 'Straight Arm Pulldown',
    primaryMuscle: PrimaryMuscle.BACK,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.CABLE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '单臂哑铃划船',
    nameEn: 'One-Arm Dumbbell Row',
    primaryMuscle: PrimaryMuscle.BACK,
    secondaryMuscles: [PrimaryMuscle.BICEPS],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: 'T杠划船',
    nameEn: 'T-Bar Row',
    primaryMuscle: PrimaryMuscle.BACK,
    secondaryMuscles: [PrimaryMuscle.BICEPS],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
];
