import {
  ExerciseDifficulty,
  ExerciseEquipment,
  PrimaryMuscle,
  type Prisma,
} from '../../../src/generated';

export const BICEPS_EXERCISES: Prisma.ExerciseCreateManyInput[] = [
  {
    nameZh: '杠铃弯举',
    nameEn: 'Barbell Curl',
    primaryMuscle: PrimaryMuscle.BICEPS,
    secondaryMuscles: [PrimaryMuscle.FOREARMS],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '哑铃弯举',
    nameEn: 'Dumbbell Curl',
    primaryMuscle: PrimaryMuscle.BICEPS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '锤式弯举',
    nameEn: 'Hammer Curl',
    primaryMuscle: PrimaryMuscle.BICEPS,
    secondaryMuscles: [PrimaryMuscle.FOREARMS],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '牧师凳弯举',
    nameEn: 'Preacher Curl',
    primaryMuscle: PrimaryMuscle.BICEPS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '绳索弯举',
    nameEn: 'Cable Curl',
    primaryMuscle: PrimaryMuscle.BICEPS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.CABLE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '集中弯举',
    nameEn: 'Concentration Curl',
    primaryMuscle: PrimaryMuscle.BICEPS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '斜板哑铃弯举',
    nameEn: 'Incline Dumbbell Curl',
    primaryMuscle: PrimaryMuscle.BICEPS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
];
