import {
  ExerciseDifficulty,
  ExerciseEquipment,
  PrimaryMuscle,
  type Prisma,
} from '../../../src/generated';

export const CHEST_EXERCISES: Prisma.ExerciseCreateManyInput[] = [
  {
    nameZh: '杠铃卧推',
    nameEn: 'Barbell Bench Press',
    primaryMuscle: PrimaryMuscle.CHEST,
    secondaryMuscles: [PrimaryMuscle.TRICEPS, PrimaryMuscle.SHOULDER],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '哑铃卧推',
    nameEn: 'Dumbbell Bench Press',
    primaryMuscle: PrimaryMuscle.CHEST,
    secondaryMuscles: [PrimaryMuscle.TRICEPS, PrimaryMuscle.SHOULDER],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '上斜哑铃卧推',
    nameEn: 'Incline Dumbbell Press',
    primaryMuscle: PrimaryMuscle.CHEST,
    secondaryMuscles: [PrimaryMuscle.SHOULDER, PrimaryMuscle.TRICEPS],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '下斜杠铃卧推',
    nameEn: 'Decline Barbell Bench Press',
    primaryMuscle: PrimaryMuscle.CHEST,
    secondaryMuscles: [PrimaryMuscle.TRICEPS],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '龙门架夹胸',
    nameEn: 'Cable Fly',
    primaryMuscle: PrimaryMuscle.CHEST,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.CABLE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '器械推胸',
    nameEn: 'Machine Chest Press',
    primaryMuscle: PrimaryMuscle.CHEST,
    secondaryMuscles: [PrimaryMuscle.TRICEPS],
    equipment: ExerciseEquipment.MACHINE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '俯卧撑',
    nameEn: 'Push-up',
    primaryMuscle: PrimaryMuscle.CHEST,
    secondaryMuscles: [PrimaryMuscle.TRICEPS, PrimaryMuscle.SHOULDER],
    equipment: ExerciseEquipment.BODYWEIGHT,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '双杠臂屈伸',
    nameEn: 'Dip',
    primaryMuscle: PrimaryMuscle.CHEST,
    secondaryMuscles: [PrimaryMuscle.TRICEPS, PrimaryMuscle.SHOULDER],
    equipment: ExerciseEquipment.BODYWEIGHT,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
];
