import {
  ExerciseDifficulty,
  ExerciseEquipment,
  PrimaryMuscle,
  type Prisma,
} from '../../../src/generated';

export const GLUTES_EXERCISES: Prisma.ExerciseCreateManyInput[] = [
  {
    nameZh: '臀推',
    nameEn: 'Hip Thrust',
    primaryMuscle: PrimaryMuscle.GLUTES,
    secondaryMuscles: [PrimaryMuscle.HAMSTRINGS],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '臀桥',
    nameEn: 'Glute Bridge',
    primaryMuscle: PrimaryMuscle.GLUTES,
    secondaryMuscles: [PrimaryMuscle.HAMSTRINGS],
    equipment: ExerciseEquipment.BODYWEIGHT,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '绳索后踢',
    nameEn: 'Cable Kickback',
    primaryMuscle: PrimaryMuscle.GLUTES,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.CABLE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '单腿硬拉',
    nameEn: 'Single-Leg Deadlift',
    primaryMuscle: PrimaryMuscle.GLUTES,
    secondaryMuscles: [PrimaryMuscle.HAMSTRINGS, PrimaryMuscle.BACK],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '蚌式开合',
    nameEn: 'Clamshell',
    primaryMuscle: PrimaryMuscle.GLUTES,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.BODYWEIGHT,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '悍马机髋外展',
    nameEn: 'Hip Abduction Machine',
    primaryMuscle: PrimaryMuscle.GLUTES,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.MACHINE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '蛙式臀桥',
    nameEn: 'Frog Pump',
    primaryMuscle: PrimaryMuscle.GLUTES,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.BODYWEIGHT,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
];
