import {
  ExerciseDifficulty,
  ExerciseEquipment,
  PrimaryMuscle,
  type Prisma,
} from '../../../src/generated';

export const HAMSTRINGS_EXERCISES: Prisma.ExerciseCreateManyInput[] = [
  {
    nameZh: '罗马尼亚硬拉',
    nameEn: 'Romanian Deadlift',
    primaryMuscle: PrimaryMuscle.HAMSTRINGS,
    secondaryMuscles: [PrimaryMuscle.GLUTES, PrimaryMuscle.BACK],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '腿弯举',
    nameEn: 'Leg Curl',
    primaryMuscle: PrimaryMuscle.HAMSTRINGS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.MACHINE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '早安式',
    nameEn: 'Good Morning',
    primaryMuscle: PrimaryMuscle.HAMSTRINGS,
    secondaryMuscles: [PrimaryMuscle.GLUTES, PrimaryMuscle.BACK],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.ADVANCED,
    isPreset: true,
  },
  {
    nameZh: '北欧腘绳肌弯举',
    nameEn: 'Nordic Hamstring Curl',
    primaryMuscle: PrimaryMuscle.HAMSTRINGS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.BODYWEIGHT,
    difficulty: ExerciseDifficulty.ADVANCED,
    isPreset: true,
  },
  {
    nameZh: '直腿硬拉',
    nameEn: 'Stiff-Leg Deadlift',
    primaryMuscle: PrimaryMuscle.HAMSTRINGS,
    secondaryMuscles: [PrimaryMuscle.GLUTES, PrimaryMuscle.BACK],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '滑轮挺髋',
    nameEn: 'Cable Pull-Through',
    primaryMuscle: PrimaryMuscle.HAMSTRINGS,
    secondaryMuscles: [PrimaryMuscle.GLUTES],
    equipment: ExerciseEquipment.CABLE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '单腿罗马尼亚硬拉',
    nameEn: 'Single-Leg Romanian Deadlift',
    primaryMuscle: PrimaryMuscle.HAMSTRINGS,
    secondaryMuscles: [PrimaryMuscle.GLUTES],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
];
