import {
  ExerciseDifficulty,
  ExerciseEquipment,
  PrimaryMuscle,
  type Prisma,
} from '../../../src/generated';

export const QUADS_EXERCISES: Prisma.ExerciseCreateManyInput[] = [
  {
    nameZh: '杠铃深蹲',
    nameEn: 'Barbell Back Squat',
    primaryMuscle: PrimaryMuscle.QUADS,
    secondaryMuscles: [PrimaryMuscle.GLUTES, PrimaryMuscle.HAMSTRINGS],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '腿举',
    nameEn: 'Leg Press',
    primaryMuscle: PrimaryMuscle.QUADS,
    secondaryMuscles: [PrimaryMuscle.GLUTES],
    equipment: ExerciseEquipment.MACHINE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '腿屈伸',
    nameEn: 'Leg Extension',
    primaryMuscle: PrimaryMuscle.QUADS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.MACHINE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '保加利亚分腿蹲',
    nameEn: 'Bulgarian Split Squat',
    primaryMuscle: PrimaryMuscle.QUADS,
    secondaryMuscles: [PrimaryMuscle.GLUTES],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '哈克深蹲',
    nameEn: 'Hack Squat',
    primaryMuscle: PrimaryMuscle.QUADS,
    secondaryMuscles: [PrimaryMuscle.GLUTES],
    equipment: ExerciseEquipment.MACHINE,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '弓步蹲',
    nameEn: 'Walking Lunge',
    primaryMuscle: PrimaryMuscle.QUADS,
    secondaryMuscles: [PrimaryMuscle.GLUTES],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '杠铃前蹲',
    nameEn: 'Front Squat',
    primaryMuscle: PrimaryMuscle.QUADS,
    secondaryMuscles: [PrimaryMuscle.GLUTES, PrimaryMuscle.ABS],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.ADVANCED,
    isPreset: true,
  },
  {
    nameZh: '登台阶',
    nameEn: 'Step-up',
    primaryMuscle: PrimaryMuscle.QUADS,
    secondaryMuscles: [PrimaryMuscle.GLUTES],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
];
