import {
  ExerciseDifficulty,
  ExerciseEquipment,
  PrimaryMuscle,
  type Prisma,
} from '../../../src/generated';

export const SHOULDER_EXERCISES: Prisma.ExerciseCreateManyInput[] = [
  {
    nameZh: '哑铃肩推',
    nameEn: 'Dumbbell Shoulder Press',
    primaryMuscle: PrimaryMuscle.SHOULDER,
    secondaryMuscles: [PrimaryMuscle.TRICEPS],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '杠铃推举',
    nameEn: 'Barbell Overhead Press',
    primaryMuscle: PrimaryMuscle.SHOULDER,
    secondaryMuscles: [PrimaryMuscle.TRICEPS],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '阿诺德推举',
    nameEn: 'Arnold Press',
    primaryMuscle: PrimaryMuscle.SHOULDER,
    secondaryMuscles: [PrimaryMuscle.TRICEPS],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '侧平举',
    nameEn: 'Lateral Raise',
    primaryMuscle: PrimaryMuscle.SHOULDER,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '前平举',
    nameEn: 'Front Raise',
    primaryMuscle: PrimaryMuscle.SHOULDER,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '面拉',
    nameEn: 'Face Pull',
    primaryMuscle: PrimaryMuscle.SHOULDER,
    secondaryMuscles: [PrimaryMuscle.BACK],
    equipment: ExerciseEquipment.CABLE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '反向飞鸟',
    nameEn: 'Reverse Fly',
    primaryMuscle: PrimaryMuscle.SHOULDER,
    secondaryMuscles: [PrimaryMuscle.BACK],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '杠铃耸肩',
    nameEn: 'Barbell Shrug',
    primaryMuscle: PrimaryMuscle.SHOULDER,
    secondaryMuscles: [PrimaryMuscle.FOREARMS],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
];
