import {
  ExerciseDifficulty,
  ExerciseEquipment,
  PrimaryMuscle,
  type Prisma,
} from '../../../src/generated';

export const TRICEPS_EXERCISES: Prisma.ExerciseCreateManyInput[] = [
  {
    nameZh: '窄距杠铃卧推',
    nameEn: 'Close-Grip Bench Press',
    primaryMuscle: PrimaryMuscle.TRICEPS,
    secondaryMuscles: [PrimaryMuscle.CHEST],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '绳索下压',
    nameEn: 'Tricep Pushdown',
    primaryMuscle: PrimaryMuscle.TRICEPS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.CABLE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '哑铃过头臂屈伸',
    nameEn: 'Dumbbell Overhead Tricep Extension',
    primaryMuscle: PrimaryMuscle.TRICEPS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '杠铃过头臂屈伸',
    nameEn: 'Barbell Overhead Tricep Extension',
    primaryMuscle: PrimaryMuscle.TRICEPS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.BARBELL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    isPreset: true,
  },
  {
    nameZh: '单臂哑铃臂屈伸',
    nameEn: 'Single-Arm Tricep Extension',
    primaryMuscle: PrimaryMuscle.TRICEPS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.DUMBBELL,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '板凳臂屈伸',
    nameEn: 'Bench Dip',
    primaryMuscle: PrimaryMuscle.TRICEPS,
    secondaryMuscles: [PrimaryMuscle.CHEST],
    equipment: ExerciseEquipment.BODYWEIGHT,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
  {
    nameZh: '反握绳索下压',
    nameEn: 'Reverse Grip Tricep Pushdown',
    primaryMuscle: PrimaryMuscle.TRICEPS,
    secondaryMuscles: [],
    equipment: ExerciseEquipment.CABLE,
    difficulty: ExerciseDifficulty.BEGINNER,
    isPreset: true,
  },
];
